### ISSUE TITLE
Installation Instructions possible enhancements

### ISSUE THREAD

**Issue by TBettens** [JaredDyreson/Tuffix-Lib#2]
Very nice!  Went through the steps and everything seems to work great for me.   Just a couple  very minor documentation observations:

Step 1: "... release some after it is ..."  => "... release sometime after it is ..."
Step 3:  double clicking Tuffix_1.0_3_x86_64.deb opened Archive Manager.  Had to right click -> open with other application -> Software Install
Step 3:  After clicking the green Install button, an "Authentication Required" box appeared.  Entered my password.
Step 6:  Showing the OS as Ubuntu is nice, but which Ubuntu release would help.  The `lsb_release -a` command gives a bit more:

            No LSB modules are available.
            Distributor ID: Ubuntu
            Description:    Ubuntu 20.04.2 LTS
            Release:        20.04
            Codename:       focal         
Q&A: Can I install a virtual machine (VM) instead of natively?  We say "No", but the screen shots in the instructions are from a VBox VM.

**Comment by kevinwortman** [comment]
Thanks!

> Step 1: "... release some after it is ..." => "... release sometime after it is ..."

Gotcha, fixed in https://github.com/CSUF-Tuffix/Tuffix-2/wiki/Installation-Instructions/94730ea8d40335fbca27bc23a3cfb186b15d15df

> Step 3: double clicking Tuffix_1.0_3_x86_64.deb opened Archive Manager. Had to right click -> open with other application -> Software Install
Step 3: After clicking the green Install button, an "Authentication Required" box appeared. Entered my password.
> Q&A: Can I install a virtual machine (VM) instead of natively? We say "No", but the screen shots in the instructions are from a VBox VM.

Good catches, it's hard to remember which steps are "obvious." I'll need to make a new set of screenshots on a native install. Let's wait a few days to see if any other corrections come in first.

> Step 6: Showing the OS as Ubuntu is nice, but which Ubuntu release would help. 

@JaredDyreson , how hard would it be to add the Ubuntu release number to the output of `tuffix status`?

**Comment by JaredDyreson** [comment]
I just pushed a fix to `devbranch` for the status command, it was not hard to implement

**Comment by kevinwortman** [comment]
Great, please let me know after you've pushed that change so I can make new screenshots.

**Comment by kevinwortman** [comment]
These improvements have been made. Thanks Thomas and Jared for the help.
